# -*- coding: utf-8 -*-
"""loader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bPQiHNlPBauvQ__IH7CkRO4mTn-mo3Hk
"""

import torch

class Dataset(torch.utils.data.Dataset):
  'Characterizes a dataset for PyTorch'
  def __init__(self, features, labels):
        'Initialization'
        self.labels = labels
        self.features = features

  def __len__(self):
        'Denotes the total number of samples'
        return self.features.shape[0]

  def __getitem__(self, index):
        'Generates one sample of data'

        # Load data and get label
        X = self.features[index, :]
        y = self.labels[index]

        return X, y