# -*- coding: utf-8 -*-
"""find_threshold.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cejeZJZuBVOW3HeMEC4pVBVv61BYSqq
"""

import numpy as np
import pandas as pd
import sklearn.metrics as metrics

def find_optimal_threshold(ground, prob):
  fpr, tpr, threshold  =  metrics.roc_curve(ground, prob)
  num_it = len(tpr)

  min_dist_idx = 0
  min_dist = 1000
  for i in range(0, num_it):

    dist = np.square(fpr[i]) + np.square(1 - tpr[i])
    
    if dist <= min_dist:
      min_dist = dist
      min_dist_idx = i
    
  return threshold[min_dist_idx]