# -*- coding: utf-8 -*-
"""sleep_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VR12wKl-8wwp9IzjtUsVmVrKLGBH1FL1
"""

import torch
# from tqdm import tqdm
from tqdm.notebook import tqdm_notebook as tqdm
import torch.nn.functional as F
import torch.nn as nn


class simple_model(nn.Module):
  def __init__(self, dim):

    super(simple_model, self).__init__()

    self.dim=dim

    self.linear1 = nn.Linear(dim, dim)

    self.linear2 = nn.Linear(dim, dim)
    self.linear3 = nn.Linear(dim, 2)
  
  def forward(self, x):
    out = torch.nn.ReLU()(self.linear1(x))

    out = torch.nn.ReLU()(self.linear2(out))
    out = torch.sigmoid(self.linear3(out))

    return out